<a href="https://colab.research.google.com/github/san031/Machine_learning-Artificial-Intelligence-Projects/blob/main/deep_learning/LSTM/LSTM_Stock_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1: Data preprocessing

Step 1: Importing libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### step 2: importing training set

In [ ]:
dataset_train = pd.read_csv('/content/sample_data/Google_Stock_Price_Train.csv')

In [ ]:
dataset_train.head()

,Date,Open,High,Low,Close,Volume
0,1/3/2012,325.25,332.83,324.97,663.59,"7,380,500"
1,1/4/2012,331.27,333.87,329.08,666.45,"5,749,400"
2,1/5/2012,329.83,330.75,326.89,657.21,"6,590,300"
3,1/6/2012,328.34,328.77,323.68,648.24,"5,405,900"
4,1/9/2012,322.04,322.29,309.46,620.76,"11,688,800"


In [ ]:
training_set = dataset_train.iloc[:,1:2].values

In [ ]:
training_set

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

#### step 3: feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler


In [ ]:
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)

In [ ]:
training_set_scaled

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

#### step 4 : creating a datastructure with 60 timestamps

In [ ]:
X_train = []
y_train = []
for i in range(60,1258):
  X_train.append(training_set_scaled[i-60:i,0])    #59th day
  y_train.append(training_set_scaled[i,0])         #60th day output value

X_train,y_train = np.array(X_train),np.array(y_train)

In [ ]:
X_train

array([[0.08581368, 0.09701243, 0.09433366, ..., 0.07846566, 0.08034452,
        0.08497656],
       [0.09701243, 0.09433366, 0.09156187, ..., 0.08034452, 0.08497656,
        0.08627874],
       [0.09433366, 0.09156187, 0.07984225, ..., 0.08497656, 0.08627874,
        0.08471612],
       ...,
       [0.92106928, 0.92438053, 0.93048218, ..., 0.95475854, 0.95204256,
        0.95163331],
       [0.92438053, 0.93048218, 0.9299055 , ..., 0.95204256, 0.95163331,
        0.95725128],
       [0.93048218, 0.9299055 , 0.93113327, ..., 0.95163331, 0.95725128,
        0.93796041]])

#### step5 : Reshaping

In [ ]:
X_train = np.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))

In [ ]:
X_train.shape

(1198, 60, 1)

# Part 2 : Building and Training the RNN

#### Step 1 : Building and importing libraries and packages

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout

In [ ]:
regressor = Sequential()

#### Adding the first LSTM Layers and some Dropout regularisation

In [ ]:
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1],1)))
regressor.add(Dropout(0.2))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


#### adding second layer (LSTM) and dropout

In [ ]:
regressor.add(LSTM(units = 50, return_sequences=True))
regressor.add(Dropout(0.2))

#### adding third layer (LSTM) and dropout



In [ ]:
regressor.add(LSTM(units = 50, return_sequences=True))
regressor.add(Dropout(0.2))

#### adding output layer

In [ ]:
regressor.add(Dense(units = 1))

#### compiling the RNN

In [ ]:
regressor.compile(optimizer='adam',loss = 'mean_squared_error')

#### model training  

In [ ]:
regressor.fit(X_train,y_train,epochs = 100,batch_size = 32)

Epoch 1/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.1256
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 4s 73ms/step - loss: 0.0862
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - loss: 0.0832
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 6s 89ms/step - loss: 0.0808
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - loss: 0.0808
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 5s 71ms/step - loss: 0.0812
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 4s 108ms/step - loss: 0.0789
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - loss: 0.0783
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 5s 72ms/step - loss: 0.0791
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - loss: 0.0781
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 4s 71ms/step - loss: 0.0781
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 72ms/step - loss: 0.0774
Epoch 13/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 6s 93ms/step - loss: 0.0771
Epoch 14/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 85ms/step - loss: 0.0771
Epoch 15/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 71ms/step - l

In [ ]:
regressor.save("stock_model.keras")

In [ ]:
from tensorflow import keras

model = keras.models.load_model("/content/stock_model.keras")

In [ ]:
model.summary()

# List all layers
for layer in model.layers:
    print(layer.name, layer.output_shape if hasattr(layer, 'output_shape') else '', layer.count_params())

# Get weights of a specific layer
weights = model.layers[0].get_weights()  # list of arrays: [kernel, bias]
print(weights[0].shape, weights[1].shape)

# Full config (architecture as JSON-like dict)
model.get_config()

# Optimizer, loss, metrics used when compiled
print(model.optimizer, model.loss)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 60, 50)         │        10,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 60, 50)         │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 60, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 60, 50)         │        20,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 60, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 60, 1)          │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 152,555 (595.92 KB)

 Trainable params: 50,851 (198.64 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 101,704 (397.29 KB)

lstm  10400
dropout  0
lstm_1  20200
dropout_1  0
lstm_2  20200
dropout_2  0
dense  51
(1, 200) (50, 200)
<keras.src.optimizers.adam.Adam object at 0x782979dcb830> mean_squared_error


## Part 3 : inferencing/ prediction

### getting real stock price of 2017

In [ ]:
dataset_test = pd.read_csv("/content/sample_data/Google_Stock_Price_Test.csv")

In [ ]:
dataset_test.head()

,Date,Open,High,Low,Close,Volume
0,1/3/2017,778.81,789.63,775.80,786.14,"1,657,300"
1,1/4/2017,788.36,791.34,783.16,786.90,"1,073,000"
2,1/5/2017,786.08,794.48,785.02,794.02,"1,335,200"
3,1/6/2017,795.26,807.90,792.20,806.15,"1,640,200"
4,1/9/2017,806.40,809.97,802.83,806.65,"1,272,400"


In [ ]:
real_stock_price = dataset_test.iloc[:,1:2].values

In [ ]:
real_stock_price

array([[778.81],
       [788.36],
       [786.08],
       [795.26],
       [806.4 ],
       [807.86],
       [805.  ],
       [807.14],
       [807.48],
       [807.08],
       [805.81],
       [805.12],
       [806.91],
       [807.25],
       [822.3 ],
       [829.62],
       [837.81],
       [834.71],
       [814.66],
       [796.86]])

#### getting the predicted stock price of 2017

In [ ]:
dataset_total = pd.concat((dataset_train['Open'], dataset_test['Open']),axis = 0)

In [ ]:
dataset_total

,Open
0,325.25
1,331.27
2,329.83
3,328.34
4,322.04
...,...
15,829.62
16,837.81
17,834.71
18,814.66


In [ ]:
len(dataset_total)

1278

In [ ]:
inputs = dataset_total[len(dataset_total)-len(dataset_test) - 60 :].values

In [ ]:
inputs

array([779.  , 779.66, 777.71, 786.66, 783.76, 781.22, 781.65, 779.8 ,
       787.85, 798.24, 803.3 , 795.  , 804.9 , 816.68, 806.34, 801.  ,
       808.35, 795.47, 782.89, 778.2 , 767.25, 750.66, 774.5 , 783.4 ,
       779.94, 791.17, 756.54, 755.6 , 746.97, 755.2 , 766.92, 771.37,
       762.61, 772.63, 767.73, 764.26, 760.  , 771.53, 770.07, 757.44,
       744.59, 757.71, 764.73, 761.  , 772.48, 780.  , 785.04, 793.9 ,
       797.4 , 797.34, 800.4 , 790.22, 796.76, 795.84, 792.36, 790.9 ,
       790.68, 793.7 , 783.33, 782.75, 778.81, 788.36, 786.08, 795.26,
       806.4 , 807.86, 805.  , 807.14, 807.48, 807.08, 805.81, 805.12,
       806.91, 807.25, 822.3 , 829.62, 837.81, 834.71, 814.66, 796.86])

In [ ]:
inputs = inputs.shape

In [ ]:
inputs = sc.transform(inputs)

ValueError: Expected 2D array, got 1D array instead:
array=[80.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.